### ISSUE TITLE
Non-functional fusermount in path

### ISSUE THREAD

**Issue by maresb** [conda-forge/libfuse-feedstock#13]
I am running @xmnlab's `s3fs-fuse` package which depends on (the `2.x` branch of) this feedstock. I am [having permissions problems](https://github.com/conda-forge/s3fs-fuse-feedstock/issues/4) which I have tracked down to `fusermount` being in `$PATH` but without `setuid`. Namely, I can make it work again after executing the following:

```bash
# First verify that we're manipulating the conda executable
ls -al $(which fusermount)

sudo chown root:root $(which fusermount)
sudo chmod u+s $(which fusermount)
```

But now I have a root-owned file in my conda environment, which is not so cool.

This problem [has already been discussed by @chrisburr and @mbargull in this PR](https://github.com/conda-forge/libfuse-feedstock/pull/5/files/2c500ad2551c76082aadc99f978d9b1cd7649ca5#r517854206), and the conclusion seems to have been that `fusermount` (technically `fusermount3` for the `master` branch) should go into `${PREFIX}/sbin` to keep it off the `$PATH`. Oddly, it seems that this decision was not actually implemented in this PR.

It was quite some effort for me to track down the problem all the way to this issue. Would it still make sense to change to `${PREFIX}/sbin`?

**Comment by maresb** [comment]
If yes, would the solution be to append `mv "${PREFIX}/bin/fusermount" "${PREFIX}/sbin/fusermount"` to `build.sh` or is there some autotools magic for that?

**Comment by mbargull** [comment]
> This problem [has already been discussed by @chrisburr and @mbargull in this PR](https://github.com/conda-forge/libfuse-feedstock/pull/5/files/2c500ad2551c76082aadc99f978d9b1cd7649ca5#r517854206), and the conclusion seems to have been that `fusermount` (technically `fusermount3` for the `master` branch) should go into `${PREFIX}/sbin` to keep it off the `$PATH`. Oddly, it seems that this decision was not actually implemented in this PR.

Oh, dear, yes, somehow I missed to commit the actual change we discussed there :facepalm: .

**Comment by maresb** [comment]
@mbargull haha, no problem. Thanks for the extremely quick response!!!
