### ISSUE TITLE
fusermount3 missing from package install

### ISSUE THREAD

**Issue by kmpaul** [conda-forge/libfuse-feedstock#2]
**Issue:**

Currently, the `libfuse` Conda-Forge package is built with the options:

```text
meson --prefix=$PREFIX --libdir=lib -Dexamples=false -Dutils=false build
```

But this does not install `fusermount3` (because of `-Dutils=false`, I presume), which is a utility needed by the `fusepy` package.  As a result, `fusepy` will error when using the Conda-Forge `libfuse` package:

```text
fuse: failed to exec fusermount3: No such file or directory
```

Can the `-Dutils=false` option be dropped (since it defaults to `true`)?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at (redacted)
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py38h32f6830_0    conda-forge
fusepy                    3.0.1                      py_0    conda-forge
indexed-bzip2             1.1.1                    pypi_0    pypi
indexed-gzip              1.1.0                    pypi_0    pypi
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libfuse                   3.9.1                hd1b7508_0    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
pip                       20.1               pyh9f0ad1d_0    conda-forge
python                    3.8.2           he5300dc_7_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
ratarmount                0.4.1                    pypi_0    pypi
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                46.1.3           py38h32f6830_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : xtar
    active env location : {PREFIXREDACTED}/miniconda3/envs/xtar
            shell level : 1
       user config file : {HOMES}/kpaul/.condarc
 populated config files : {HOMES}/kpaul/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.22
       base environment : {PREFIXREDACTED}  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : {PREFIXREDACTED}/miniconda3/pkgs
                          {HOMES}/kpaul/.conda/pkgs
       envs directories : {PREFIXREDACTED}/miniconda3/envs
                          {HOMES}/kpaul/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/4.12.14-95.37.1.18642.1.PTF.1155508-default sles/12.4 glibc/2.22
                UID:GID : 23889:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by kmpaul** [comment]
I would be happy to submit a PR to change this if there was general approval.

**Comment by bgruening** [comment]
Please do so @kmpaul! Thanks lot!

**Comment by kmpaul** [comment]
@bgruening Just FYI.  This turned into a bigger project than I was expecting.  I'm still working on it.  Currently, making this work requires getting some kernel-devel headers that are not available in the default conda build environment.  Which will mean creating a package for that, first.  I'll check in periodically while I'm getting that working.

**Comment by bgruening** [comment]
@kmpaul please have a look at https://conda-forge.org/docs/maintainer/knowledge_base.html#yum-deps

I don't know if this helps or is portable ... but maybe worth a try.

**Comment by kmpaul** [comment]
Yeah.  I'm concerned that the `yum_requirements.txt` file only seems to be encouraged for *testing*.  Not sure if they support it for building.

**Comment by andersy005** [comment]
> I'm concerned that the yum_requirements.txt file only seems to be encouraged for testing. Not sure if they support it for building.

When a system dependency is missing from the official docker image used by conda-forge, `yum_requirements.txt` is the way to go. We had to use  it for cudatoolkit-dev:

https://github.com/conda-forge/cudatoolkit-dev-feedstock/blob/master/recipe/yum_requirements.txt

**Comment by kmpaul** [comment]
Well, I think I hit a snag.  I should have seen this coming, but for some reason I was being naive.

The `libfuse` build system makes assumptions (if you are building the `utils` components) that you have `root` permissions to setuid root on `fusermount3` (which can actually be disabled with `-Duseroot=false`) and to install the udev rules and `init_script`.  It is unclear to me whether you can even *install* `libfuse` as a non-root/sudo user in a way that will work.

@bgruening Do you have any thoughts on this?  Can a non-root user install `libfuse` utilities in userspace?

**Comment by kmpaul** [comment]
I think this has gone stale.  And I don't need it anymore.  So, I'll close this issue.
