### ISSUE TITLE
Package for 2.x series

### ISSUE THREAD

**Issue by xmnlab** [conda-forge/libfuse-feedstock#6]
Hi everyone!

I am playing with a library called `s3fs-fuse` and I would like to create a conda package for it.  But, as `s3fs-fuse` depends on `libfuse >2.8.4,<3`, I am wondering if we can have an extra package here (in another branch) for 2.x series.

I have an initial recipe for libfuse 2.x that I am using locally, I can open a PR.

I know that libfuse 2 is very old, but as it seems that there is no plan for s3fs-fuse to use libfuse 3 (https://github.com/s3fs-fuse/s3fs-fuse/issues/1159), to create a conda package for s3fs-fuse would require a conda package for libfuse 2.x. 

cc @ocefpaf

Thanks!

**Comment by ocefpaf** [comment]
> I am wondering if we can have an extra package here (in another branch) for 2.x series.

I created the branch for you in https://github.com/conda-forge/libfuse-feedstock/tree/2.x

> I know that libfuse 2 is very old, but as it seems that there is no plan for s3fs-fuse to use libfuse 3 (s3fs-fuse/s3fs-fuse#1159), to create a conda package for s3fs-fuse would require a conda package for libfuse 2.x.

You can work on that branch and, once merged, we would produce the 2.x version. Good luck!

**Comment by xmnlab** [comment]
sounds great! thanks @ocefpaf !

**Comment by xmnlab** [comment]
resolved by #7
